// <auto-generated />
namespace CovidAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changed_column_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_column_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241056397_changed_column_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
